package dns

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/obhod/obhoud/internal/uci"
)

const dnsmasqConfDir = "/tmp/dnsmasq.d"
const obhodConfFile = "/tmp/dnsmasq.d/obhod.conf"

func ConfigureDnsmasq(cfg *uci.UciConfig, dnsPort int) error {
	if err := os.MkdirAll(dnsmasqConfDir, 0755); err != nil {
		return fmt.Errorf("failed to create dnsmasq.d dir: %w", err)
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Auto-generated by Obhod\n"))

	domainMap := make(map[string]bool)
	for _, rule := range cfg.Routing {
		for _, domain := range rule.Domains {
			if !domainMap[domain] {
				domainMap[domain] = true
				sb.WriteString(fmt.Sprintf("server=/%s/127.0.0.1#%d\n", domain, dnsPort))
				// Also mark the domain for ipset/nftset?
				// Since we use FakeIP, sing-box handles the resolution and returns a FakeIP (198.18.x.x)
				// The returned IP is automatically routed via Tproxy because of the nftables mangle rule
				// targeting 198.18.0.0/15!
			}
		}
	}

	if err := os.WriteFile(obhodConfFile, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write obhod.conf: %w", err)
	}

	log.Println("Wrote dnsmasq config to", obhodConfFile)
	return nil
}

func RemoveDnsmasqConfig() error {
	if err := os.Remove(obhodConfFile); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

func ReloadDnsmasq() error {
	// Let's use standard procd reload or SIGHUP
	cmd := exec.Command("killall", "-SIGHUP", "dnsmasq")
	return cmd.Run()
}